// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	withdraw "business-platform/app/exchange/internal/handler/withdraw"
	"business-platform/app/exchange/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建提现订单
				Method:  http.MethodPost,
				Path:    "/withdraw/create",
				Handler: withdraw.WithdrawHandler(serverCtx),
			},
			{
				// 查询提现订单列表
				Method:  http.MethodGet,
				Path:    "/withdraw/list",
				Handler: withdraw.ListWithdrawOrdersHandler(serverCtx),
			},
			{
				// 查询提现订单详情
				Method:  http.MethodGet,
				Path:    "/withdraw/order",
				Handler: withdraw.GetWithdrawOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
